language: php
dist: trusty
sudo: false

php:
- "7.2"
node_js:
- "11"

addons:
  apt:
    packages:
      - libgconf-2-4

env:
  global:
  - DRUPAL_BUILD_DIR=$TRAVIS_BUILD_DIR/../drupal
  - COMPOSER_MEMORY_LIMIT=-1

cache:
  directories:
  - node_modules
  - ~/.npm
  - ~/.cache
  - ~/.composer/cache

before_install:
- echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- phpenv config-rm xdebug.ini
- composer self-update
- nvm install 11

install:
- nvm use 11
- cd $TRAVIS_BUILD_DIR/docs && npm install -g vuepress
- composer create-project drupal-composer/drupal-project:8.x-dev $DRUPAL_BUILD_DIR --no-interaction
- cd $DRUPAL_BUILD_DIR
- composer remove drupal/core
- php -r "\$json = json_decode(file_get_contents('composer.json'), TRUE); \$json['repositories'][] = ['type' => 'path', 'url' => '$TRAVIS_BUILD_DIR' ]; file_put_contents('composer.json', json_encode(\$json, JSON_PRETTY_PRINT));"
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo $BRANCH
- composer require "amazeelabs/silverback:dev-$BRANCH"
- ./vendor/bin/silverback init
- composer install
- source .envrc
- yarn

script:
- silverback download-tests
- cp cypress/integration/jira/SLB/* vendor/amazeelabs/silverback/cypress/integration
- vendor/bin/silverback setup && vendor/bin/drush en cypress -y
- vendor/bin/drush cypress:list
- silverback-test silverback
- cd $TRAVIS_BUILD_DIR/docs && npm run build
- kill $(jobs -p) || true

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: $TRAVIS_BUILD_DIR/docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  repo: AmazeeLabs/silverback
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master
